"""Configuration module for the Urban Heat Island Analyzer."""

from .settings import *

__all__ = [
    # Coordinate System Configuration
    "CRS_CONFIG",
    
    # WFS Configuration
    "WFS_ENDPOINTS",
    "WFS_HEADERS", 
    "WFS_TIMEOUT",
    
    # Corine Configuration
    "CORINE_BASE_URLS",
    "CORINE_YEARS",
    "CORINE_LANDUSE_MAPPING",
    "CORINE_IMPERVIOUS_COEFFICIENTS",
    "DEFAULT_RECORD_COUNT",
    "DEFAULT_TIMEOUT",
    "DEFAULT_OUTPUT_FORMAT",
    
    # DWD Configuration
    "DWD_SETTINGS",
    "DWD_TEMPERATURE_PARAMETERS",
    "DWD_BUFFER_DISTANCE",
    "DWD_INTERPOLATION_RESOLUTION",
    "DWD_INTERPOLATION_METHOD",
    "DWD_INTERPOLATE_BY_DEFAULT",
    
    # UHI Analyzer Configuration
    "UHI_EARTH_ENGINE_PROJECT",
    "UHI_CLOUD_COVER_THRESHOLD",
    "UHI_LANDSAT_COLLECTION",
    "UHI_TEMPERATURE_BAND",
    "UHI_SCALE",
    "UHI_MAX_PIXELS",
    "UHI_TEMP_MULTIPLIER",
    "UHI_TEMP_ADDEND",
    "UHI_KELVIN_OFFSET",
    "UHI_GRID_CELL_SIZE",
    "UHI_HOTSPOT_THRESHOLD",
    "UHI_MIN_CLUSTER_SIZE",
    "UHI_MORAN_SIGNIFICANCE",
    "UHI_PERCENTILES",
    "UHI_CORRELATION_THRESHOLD",
    "UHI_VISUALIZATION_DPI",
    "UHI_VISUALIZATION_FIGSIZE",
    "UHI_TEMPERATURE_COLORMAP",
    "UHI_LOG_DIR",
    "UHI_LOG_LEVEL",
] 